[build]
  command = "npm run build"
  publish = "dist"

# (optionnel) forcer Node si besoin côté CI
[build.environment]
  NODE_VERSION = "18"

# Préview (utilisé par Visual Editor)
[context.preview]
  command = "npm run build"
