[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"[[edge_functions]]
  path = "/_stackbit"
  function = "stackbit-redirect"

[[edge_functions]]
  path = "/_stackbit/*"
  function = "stackbit-redirect"
